=== QRouland/sda/tp4/xml/expr.dtd
<!ELEMENT expr (binop | variable | integer)>
<!ELEMENT binop (expr, expr)>
<!ATTLIST binop op (add|sub|mul|div) #REQUIRED>
<!ELEMENT variable EMPTY>
<!ATTLIST variable name CDATA #REQUIRED>
<!ELEMENT integer (#PCDATA)>

=== QRouland/sda/tp4/xml/decoupage2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE expr SYSTEM "expr.dtd">
<!-- Original expression : (b*b)-(4*a*c) -->
<expr>
 <binop op="sub" >
  <expr>
   <binop op="mul" >
    <expr>
     <variable name="b" />
    </expr>
    <expr>
     <variable name="b" />
    </expr>
   </binop>
  </expr>
  <expr>
   <binop op="mul" >
    <expr>
     <binop op="mul" >
      <expr>
       <integer>4</integer>
      </expr>
      <expr>
       <variable name="a" />
      </expr>
     </binop>
    </expr>
    <expr>
     <variable name="c" />
    </expr>
   </binop>
  </expr>
 </binop>
</expr>

=== QRouland/sda/tp4/xml/decoupage1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE expr SYSTEM "expr.dtd">
<!-- Original expression : 1+(10+(100+1000)) -->
<expr>
 <binop op="add" >
  <expr>
   <integer>1</integer>
  </expr>
  <expr>
   <binop op="add" >
    <expr>
     <integer>10</integer>
    </expr>
    <expr>
     <binop op="add" >
      <expr>
       <integer>100</integer>
      </expr>
      <expr>
       <integer>1000</integer>
      </expr>
     </binop>
    </expr>
   </binop>
  </expr>
 </binop>
</expr>

=== QRouland/sda/tp4/xml/decoupage4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE expr SYSTEM "expr.dtd">
<!-- Original expression : x/(2*a) -->
<expr>
 <binop op="div" >
  <expr>
   <variable name="x" />
  </expr>
  <expr>
   <binop op="mul" >
    <expr>
     <integer>2</integer>
    </expr>
    <expr>
     <variable name="a" />
    </expr>
   </binop>
  </expr>
 </binop>
</expr>

=== QRouland/sda/tp4/xml/decoupage3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE expr SYSTEM "expr.dtd">
<!-- Original expression : a+x-1 -->
<expr>
 <binop op="sub" >
  <expr>
   <binop op="add" >
    <expr>
     <variable name="a" />
    </expr>
    <expr>
     <variable name="x" />
    </expr>
   </binop>
  </expr>
  <expr>
   <integer>1</integer>
  </expr>
 </binop>
</expr>
